spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universe
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false